# Generated by Django 5.2.6 on 2025-09-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
